### ISSUE TITLE
option to make a new presentation

### ISSUE THREAD

**Issue by VeraZab** [FormidableLabs/spectacle-editor#185] opened 2016-09-05 23:01 UTC
Should I not have the option somewhere here to make a new presentation?
![screen shot 2016-09-05 at 7 00 35 pm](https://cloud.githubusercontent.com/assets/4257572/18257990/1f52f1aa-739b-11e6-9d19-e495c500f563.png)

**Comment by rgerstenberger** [comment] 2016-09-06 16:21
Duplicate of #161

**Closed by rgerstenberger** 2016-09-06 16:21 UTC
