### ISSUE TITLE
File->Open throws error. 

### ISSUE THREAD

**Issue by mdtusz** [FormidableLabs/spectacle-editor#147] opened 2016-08-19 14:04 UTC
Reproduction: 

1. Open application.
2. Close main window.
3. Click on `File` -> `Open`

<img width="443" alt="screen shot 2016-08-19 at 9 59 37 am" src="https://cloud.githubusercontent.com/assets/6494463/17812249/39f4a990-65f4-11e6-9a8d-1423e6377543.png">

**Comment by rgerstenberger** [comment] 2016-08-19 16:33
@mdtusz was this with a new saved file? We changed the format of the saved file to match the upload so it could be the old file structure is not supported.

**Comment by bmathews** [comment] 2016-08-19 16:37
@rgerstenberger The issue is that `File > Open` option expects mainWindow to be defined. 

```
        label: "Open",
        accelerator: "Command+O",
        click() {
          mainWindow.webContents.send("file", "open");
        }
```

**Comment by rgerstenberger** [comment] 2016-08-19 16:42
OOOOOOOOH, yes, we don't have good handling around closing the main window, this is a very good catch. @bmathews do you know of a quick/solid fix for this. Should closing the main window just hide it until the user interacts with our app again?

**Comment by bmathews** [comment] 2016-08-19 16:53
Three-ish options:

1) Quit the app completely if the main window is closed (relatively common, 10 mins of work)
2) Update menu code to allow for the main window to be open/closed arbitrarily (~1 hour of work)
3) Allow for multiple windows/presentations to be open (TBD hours of work)

**Comment by rgerstenberger** [comment] 2016-08-19 17:13
Definitely not 3. My only concern with 1 is that we don't have a prompt for unsaved work so it could be really bad UX. Just added that issue https://github.com/FormidableLabs/spectacle-editor/issues/149. 

My vote is for 2 since I think that's a little more common on OSX. On windows, I don't know. 

Note: This is lower priority than getting viewer component shippable.

**Closed** 2016-08-19 23:55 UTC
